# .github/workflows/chromatic.yml

name: 'Chromatic'
on:
  pull_request:
    branches: [main]
  push:
    branches:
      - main

defaults:
  run:
    # This ensures that the working directory is the root of the repository
    working-directory: packages/core/

# List of jobs
jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    # environment:
    #   name: Storybook
    #   url: ${{ steps.chromatic-deploy.outputs.storybookUrl }}

    steps:
      - uses: actions/checkout@v1
      - uses: volta-cli/action@v1
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Build Storybook
        # Assigns an ID to be reused on other steps
        id: storybook_build
        run: yarn build-storybook

      - name: Start Visual Regression Tests (Chromatic)
         # This assigns the Environment Deployment for Storybook
        id: chromatic-deploy
        if: steps.storybook_build.outcome == 'success'
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: packages/core/
          exitOnceUploaded: true

      - name: Publish Summary
        id: publish-summary
        run: |
          echo -e "| Results |  |\n| --- | --- |\n| Build Results | ${{steps.chromatic-deploy.outputs.buildUrl}} |\n| Storybook Preview | ${{steps.chromatic-deploy.outputs.storybookUrl}} |\n| Component Count | ${{steps.chromatic-deploy.outputs.componentCount}} |" >> $GITHUB_WORKSPACE/summary.md
          echo "::set-output name=GITHUB_STEP_SUMMARY::$(cat $GITHUB_WORKSPACE/summary.md)"

      - name: Comment Publish Summary
        uses: actions/github-script@v4
        with:
          script: |
             const fs = require('fs');
             const path = require('path');
             const message = fs.readFileSync(path.join(process.env.GITHUB_WORKSPACE, 'summary.md'), 'utf8');
             github.issues.createComment({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
               body: message,
             });
